### ISSUE TITLE
This is not a problem but..

### ISSUE THREAD

**Issue by brutalzinn** [kaualandi/wa-api-official#1]
Dude, you .env file its commited to repo. I dont know you objectives or If this is proposal but keep secure your envs!

**Comment by kaualandi** [comment]
My dear, this env is an example, they were once real but they are invalid. They are there so that I can remember the structures of the keys, since the code is very old.

**Comment by brutalzinn** [comment]
Perfect!

**Comment by kaualandi** [comment]
not a problem
